name: MineCombat
version: "1.0"
author: onebone
authors: [onebone, Khinenw]
main: onebone\minecombat\MineCombat
api: [3.0.0-ALPHA3, 3.0.0-ALPHA4]

permissions:
 minecombat.*:
  description: Includes all permissions of MineCombat
  children:
   minecombat.command.*:
    description: Includes all permissions to use command of MineCombat
    children:
     minecombat.command.rank:
      description: Allows player to use /rank
      default: true
      usage: /rank
     minecombat.command.spawnpos:
      description: Allows player to use /spawnpos
      usage: /spawnpos <blue|red>
     minecombat.command.momap:
      description: Allows player to use /momap
      usage: /momap <name>

commands:
 rank:
  usage: /rank
  description: Allows player to see their rank
  permission: minecombat.command.rank
 spawnpos:
  usage: /spawnpos <blue|red|list>
  description: Allows player to set spawn position of each team.
  permission: minecombat.command.spawnpos
 momap:
  usage: /momap <name>
  description: Allows player to modify map by hand
  permission: minecombat.command.momap
